/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const mount_admin_app: () => [number, number];
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h104829505029017a: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hde305db5d3849056: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h597a50b6ddf79191: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h33a1835798703fcb: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h49bbdbbf2d3431fb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h0e3fb0c119504822: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h535821c1b5368d37: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hd5b6c33430620d09: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h90c59cb4d882c183: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__haff7f3b68957d50c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8e0db29656939dc9: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__heb91d646fcb6f780: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h09110f03699d3c72: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hd66e82646e2a57df: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h69ac4cf9bb407d6c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h86bfcb4c5d2fae81: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
