/* auto-generated by NAPI-RS (mocked) */
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const require = createRequire(import.meta.url)

// --- Native Binding ---

export interface CreateAccountOutput {
  success: boolean
  signedTransaction?: string
  walletAddress?: string
  tokenAccountAddress?: string
  mint?: string
  error?: string
}

export function createAccountTransaction(
  keypairPath: string,
  mintAddress: string,
  rpcUrl: string
): CreateAccountOutput {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const native = require('../../../../../../../rust_shared/target/release/index.node')
  return native.signCreateAccountRequest(keypairPath, rpcUrl)
}

// --- High Level Helpers ---

export interface CreateAccountSignedBody {
    wallet_address: string
    token_account_address: string
    signed_transaction: string
}

function readJson(filePath: string) {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'))
}

/**
 * Prepares the signed body for the /api/splitdo-token/accounts/create endpoint
 * by reading the local config and signing with the local wallet.
 */
export function signCreateAccountRequest(walletPath: string): CreateAccountSignedBody {
    // 1. Find Config
    let configPath = path.resolve(__dirname, '../../../../../../../../solana/splitdo_config.json')
    
    if (!fs.existsSync(configPath)) {
        // Fallback 1: Try relative to CWD
        configPath = path.resolve('../../solana/splitdo_config.json')
    }

    if (!fs.existsSync(configPath)) {
         // Fallback 2: Try absolute path
         configPath = path.resolve('/home/opc/splitdo/original/solana/splitdo_config.json')
    }
    
    if (!fs.existsSync(configPath)) {
        throw new Error(`[signCreateAccountRequest] Config not found at ${configPath} or CWD`)
    }

    const config = readJson(configPath)
    const mint = config.splitdo_mint
    const rpcUrl = "https://api.mainnet-beta.solana.com"

    console.log(`[RustBinding] Inputs:`)
    console.log(`  Wallet: ${walletPath}`)
    console.log(`  Mint:   ${mint}`)
    console.log(`  RPC:    ${rpcUrl}`)

    // 2. Sign
    const signResult = createAccountTransaction(walletPath, mint, rpcUrl)
    
    console.log(`[RustBinding] Result Content: {
      walletAddress: ${signResult.walletAddress},
      tokenAccountAddress: ${signResult.tokenAccountAddress},
      signedTransaction: ${signResult.signedTransaction ? signResult.signedTransaction.substring(0, 50) + '...' : 'undefined'}
    }`)

    // The shared library throws on error, so if we are here, it succeeded.
    // The structure is { walletAddress, tokenAccountAddress, signedTransaction } (camelCase from NAPI)

    if (!signResult.walletAddress || !signResult.tokenAccountAddress || !signResult.signedTransaction) {
        throw new Error(`[signCreateAccountRequest] Signing returned incomplete data`)
    }

    return {
        wallet_address: signResult.walletAddress,
        token_account_address: signResult.tokenAccountAddress,
        signed_transaction: signResult.signedTransaction
    }
}
