/* auto-generated by NAPI-RS (mocked) */
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const require = createRequire(import.meta.url)

// --- Native Binding ---

export interface TransferOutput {
  success: boolean
  signedTransaction?: string
  fromAta?: string
  toAta?: string
  amount?: number
  mint?: string
  error?: string
}

export function createTransferTransaction(
  keypairPath: string,
  fromAtaStr: string,
  toAtaStr: string,
  amount: number,
  mintAddress: string,
  rpcUrl: string
): TransferOutput {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const native = require('../../../../../../rust_shared/target/release/index.node')
  return native.signTransferRequest(keypairPath, fromAtaStr, toAtaStr, amount)
}

// --- High Level Helpers ---

export interface TransferSignedBody {
    to_user_id: string
    amount_tokens: number
    signed_transaction: string
    memo?: string
}

function readJson(filePath: string) {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'))
}

/**
 * Signs a transfer transaction.
 * 
 * @param walletPath Path to sender's keypair.json
 * @param fromAta Sender's Token Account Address
 * @param toAta Recipient's Token Account Address (Must be known/derived beforehand!)
 * @param recipientUserId Recipient's User ID (for the API body)
 * @param amountTokens Amount of tokens to transfer (e.g. 100.0)
 */
export function signTransferRequest(
    walletPath: string, 
    fromAta: string, 
    toAta: string, 
    recipientUserId: string,
    amountTokens: number
): TransferSignedBody {
    // 1. Find Config
    // We are at .../transfer/rust/index.ts (8 levels deep)
    let configPath = path.resolve(__dirname, '../../../../../../../../solana/splitdo_config.json')
    
    if (!fs.existsSync(configPath)) {
        configPath = path.resolve('../../solana/splitdo_config.json')
    }
    if (!fs.existsSync(configPath)) {
         configPath = path.resolve('/home/opc/splitdo/original/solana/splitdo_config.json')
    }
    if (!fs.existsSync(configPath)) {
        throw new Error(`[signTransferRequest] Config not found at ${configPath}`)
    }

    const config = readJson(configPath)
    const mint = config.splitdo_mint
    const rpcUrl = "http://localhost:8899"

    // Convert amount to raw units (6 decimals)
    // 100.0 -> 100,000,000
    const rawAmount = Math.floor(amountTokens * 1_000_000)

    console.log(`[RustBinding] Inputs:`)
    console.log(`  Wallet:   ${walletPath}`)
    console.log(`  From ATA: ${fromAta}`)
    console.log(`  To ATA:   ${toAta}`)
    console.log(`  Amount:   ${amountTokens} (${rawAmount} raw)`)
    console.log(`  Mint:     ${mint}`)

    // 2. Sign
    const signResult = createTransferTransaction(
        walletPath, 
        fromAta, 
        toAta, 
        rawAmount, 
        mint, 
        rpcUrl
    )

    console.log(`[RustBinding] Raw Result Keys:`, Object.keys(signResult))
    console.log(`[RustBinding] Signed Tx Length:`, signResult.signedTransaction ? signResult.signedTransaction.length : 'undefined')

    // Rust throws on error.
    if (!signResult.signedTransaction) {
        throw new Error(`[signTransferRequest] Signing returned no transaction`)
    }

    return {
        to_user_id: recipientUserId,
        amount_tokens: amountTokens,
        signed_transaction: signResult.signedTransaction
    }
}
